name: Build apk on merge
'on':
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Install Dependencies
        run: flutter pub get
      - name: Test
        run: flutter test
      - name: Build
        run: flutter build apk
      - name: Archive Build Artifact
        uses: actions/upload-artifact@master
        with:
            name: build
            path: build
